#!/usr/bin/env python3
"""
Generate visual-inspection panels for TopoAware SR observation groups.

Run from the scripts directory:

    cd ~/PhIRE/scripts
    PYTHONNOUSERSITE=1 /usr/bin/python3 generate_visual_inspection_panels.py

The script auto-detects the PhIRE repository root and uses the final repaired
artifacts by default:

    data_out_fixed/wind_mrhr_cnn/
    data_out_fixed/wind_mrhr_gan/
    ttk_runs_fixed/observation_groups/
    ttk_runs_fixed/visual_inspection/

Default behavior
----------------
The default preset is `paper_audit`. It generates one speed/error panel per
unique recommended visual-inspection sample plus the core control samples.

Each panel contains:

    GT speed | CNN speed | GAN speed | |CNN-GT| |GAN-GT|

By default, the panel uses the 160x160 crop used by the topology evaluation.
Use `--include-full-panels` to also generate full 500x500 panels.

Why this exists
---------------
The quantitative audit showed that:
  - PSNR/SSIM/direct-error metrics are strongly CNN-facing,
  - several distributional/tail metrics support GAN,
  - bottleneck PD is strongly GAN-facing,
  - MT is intermediate,
  - PD-MT disagreement identifies candidate structural-hallucination cases.

The visual-inspection panels are meant to determine whether GAN-favored
topological/distributional structure is physically meaningful or visually sharp
but spatially/hierarchically misaligned.
"""

from __future__ import annotations

import argparse
import csv
import html
import math
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

# Must be set before importing pyplot on headless Spark nodes.
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


CORE_CONTRAST_SAMPLES = [8, 12, 25, 27, 31, 37, 39, 29, 32]
MT_PRIMARY_CONTROL_SAMPLES = [27, 31, 37, 39, 29, 32]
NEARTIE_DISAGREEMENT_SAMPLES = [8, 12, 25]
MT_GAN_DIAGNOSTIC_SAMPLES = [6, 8, 12, 16, 17, 18, 19, 20, 25, 48,
                             62, 63, 65, 68, 77, 79, 80, 82, 92, 154]
TOPOLOGY_CONSENSUS_CNN_SAMPLES = [162, 163]


def discover_repo_root(explicit: Optional[Path] = None) -> Path:
    """Find repo root when the script is run from either ~/PhIRE or ~/PhIRE/scripts."""
    if explicit is not None:
        return explicit.expanduser().resolve()

    cwd = Path.cwd().resolve()
    script_dir = Path(__file__).resolve().parent

    def looks_like_repo_root(cand: Path) -> bool:
        cand = cand.resolve()
        if cand.name == "scripts":
            return False
        if (cand / "data_out_fixed").is_dir() and (cand / "ttk_runs_fixed").is_dir():
            return True
        if (cand / "scripts").is_dir() and (
            (cand / "data_out_fixed").is_dir()
            or (cand / "ttk_runs_fixed").is_dir()
            or (cand / "data_out").is_dir()
            or (cand / ".git").exists()
        ):
            return True
        return False

    candidates: List[Path] = []
    if cwd.name == "scripts":
        candidates.append(cwd.parent)
    if script_dir.name == "scripts":
        candidates.append(script_dir.parent)

    for start in [cwd, script_dir]:
        candidates.append(start)
        candidates.extend(start.parents)

    seen = set()
    for cand in candidates:
        cand = cand.resolve()
        if cand in seen:
            continue
        seen.add(cand)
        if looks_like_repo_root(cand):
            return cand

    if cwd.name == "scripts":
        return cwd.parent
    if script_dir.name == "scripts":
        return script_dir.parent
    return cwd


def resolve_project_path(path: Path, repo_root: Path) -> Path:
    path = path.expanduser()
    if path.is_absolute():
        return path
    return (repo_root / path).resolve()


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--repo-root", type=Path, default=None,
                   help="Optional explicit PhIRE repository root.")
    p.add_argument("--cnn-dir", type=Path, default=Path("data_out_fixed/wind_mrhr_cnn"),
                   help="Fixed CNN output directory. Relative paths resolve from repo root.")
    p.add_argument("--gan-dir", type=Path, default=Path("data_out_fixed/wind_mrhr_gan"),
                   help="Fixed GAN output directory. Relative paths resolve from repo root.")
    p.add_argument("--groups-dir", type=Path, default=Path("ttk_runs_fixed/observation_groups"),
                   help="Observation group directory generated by generate_observation_groups.py.")
    p.add_argument("--outdir", type=Path, default=Path("ttk_runs_fixed/visual_inspection"),
                   help="Output directory for visual-inspection panels.")
    p.add_argument("--preset", choices=["starter", "paper_audit", "all_observation_groups"],
                   default="paper_audit",
                   help=(
                       "starter: 9-sample contrast set. "
                       "paper_audit: recommended unique samples plus controls. "
                       "all_observation_groups: all samples appearing in any observation group."
                   ))
    p.add_argument("--crop-size", type=int, default=160,
                   help="Crop size for default panels. Use 160 to match topology-evaluation crop.")
    p.add_argument("--crop-origin", type=int, nargs=2, default=[0, 0], metavar=("Y0", "X0"),
                   help="Top-left crop origin as Y0 X0. Default is 0 0.")
    p.add_argument("--include-full-panels", action="store_true",
                   help="Also generate full-field 500x500 panels.")
    p.add_argument("--include-uv-panels", action="store_true",
                   help="Also generate optional u/v component panels.")
    p.add_argument("--max-candidate-hallucination", type=int, default=20,
                   help="Number of top candidate structural-hallucination samples to include in paper_audit if recommended file is absent.")
    p.add_argument("--max-gan-distributional", type=int, default=20,
                   help="Number of top GAN-distributional samples to include in paper_audit if recommended file is absent.")
    return p.parse_args()


def read_csv_dicts(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", newline="") as f:
        return list(csv.DictReader(f))


def read_sample_ids(path: Path) -> List[int]:
    if not path.exists():
        return []
    text = path.read_text().strip()
    if not text:
        return []
    vals: List[int] = []
    for tok in text.replace("\n", ",").split(","):
        tok = tok.strip()
        if tok:
            vals.append(int(float(tok)))
    return vals


def ordered_unique(values: Iterable[int]) -> List[int]:
    out: List[int] = []
    seen = set()
    for v in values:
        iv = int(v)
        if iv not in seen:
            seen.add(iv)
            out.append(iv)
    return out


def build_group_map(groups_dir: Path) -> Dict[str, List[int]]:
    """Load available observation-group sample lists, with hardcoded fallbacks."""
    group_map: Dict[str, List[int]] = {}

    sample_id_files = {
        "neartie_topology_validator_disagreement": "sample_ids_neartie_topology_validator_disagreement.txt",
        "mt_gan_diagnostic": "sample_ids_mt_gan_diagnostic.txt",
        "topology_consensus_gan": "sample_ids_topology_consensus_gan.txt",
        "topology_consensus_cnn": "sample_ids_topology_consensus_cnn.txt",
        "candidate_structural_hallucination_signature": "sample_ids_candidate_structural_hallucination_signature.txt",
        "gan_distributional_cases": "sample_ids_gan_distributional_cases.txt",
        "cnn_consensus_core": "sample_ids_cnn_consensus_core.txt",
        "recommended_visual_inspection_unique": "sample_ids_recommended_visual_inspection_unique.txt",
    }

    for name, fn in sample_id_files.items():
        ids = read_sample_ids(groups_dir / fn)
        if ids:
            group_map[name] = ids

    group_map.setdefault("neartie_topology_validator_disagreement", NEARTIE_DISAGREEMENT_SAMPLES)
    group_map.setdefault("mt_gan_diagnostic", MT_GAN_DIAGNOSTIC_SAMPLES)
    group_map.setdefault("topology_consensus_gan", MT_GAN_DIAGNOSTIC_SAMPLES)
    group_map.setdefault("topology_consensus_cnn", TOPOLOGY_CONSENSUS_CNN_SAMPLES)
    group_map.setdefault("cnn_consensus_core", MT_PRIMARY_CONTROL_SAMPLES)

    return group_map


def load_per_sample_metadata(groups_dir: Path) -> Dict[int, Dict[str, str]]:
    rows = read_csv_dicts(groups_dir / "observation_groups_per_sample.csv")
    out: Dict[int, Dict[str, str]] = {}
    for row in rows:
        try:
            out[int(float(row["sample_idx"]))] = row
        except Exception:
            continue
    return out


def load_arrays(cnn_dir: Path, gan_dir: Path) -> Dict[str, np.ndarray]:
    required = [
        cnn_dir / "dataGT.npy",
        cnn_dir / "dataSR.npy",
        cnn_dir / "idx.npy",
        gan_dir / "dataGT.npy",
        gan_dir / "dataSR.npy",
        gan_dir / "idx.npy",
    ]
    missing = [p for p in required if not p.exists()]
    if missing:
        raise SystemExit("Missing required arrays:\n" + "\n".join(str(p) for p in missing))

    arrays = {
        "cnn_gt": np.load(cnn_dir / "dataGT.npy", mmap_mode="r"),
        "cnn_sr": np.load(cnn_dir / "dataSR.npy", mmap_mode="r"),
        "cnn_idx": np.load(cnn_dir / "idx.npy", mmap_mode="r"),
        "gan_gt": np.load(gan_dir / "dataGT.npy", mmap_mode="r"),
        "gan_sr": np.load(gan_dir / "dataSR.npy", mmap_mode="r"),
        "gan_idx": np.load(gan_dir / "idx.npy", mmap_mode="r"),
    }
    return arrays


def build_idx_lookup(idx: np.ndarray) -> Dict[int, int]:
    return {int(v): i for i, v in enumerate(np.asarray(idx).tolist())}


def speed(arr: np.ndarray) -> np.ndarray:
    return np.sqrt(arr[..., 0] ** 2 + arr[..., 1] ** 2)


def crop_field(field: np.ndarray, y0: int, x0: int, crop_size: Optional[int]) -> np.ndarray:
    if crop_size is None:
        return np.asarray(field)
    return np.asarray(field[y0:y0 + crop_size, x0:x0 + crop_size])


def short_groups_for_sample(sample_id: int, group_map: Dict[str, List[int]]) -> str:
    hits = []
    for name, ids in group_map.items():
        if sample_id in set(ids):
            hits.append(name)
    return ";".join(sorted(hits))


def metadata_title(sample_id: int, metadata: Dict[int, Dict[str, str]]) -> str:
    row = metadata.get(sample_id, {})
    if not row:
        return f"sample {sample_id}"
    parts = [
        f"sample {sample_id}",
        f"SSIM={row.get('ssim_winner', '?')}",
        f"PD={row.get('pd_winner', '?')}",
        f"MT={row.get('mt_winner', '?')}",
        f"direct={row.get('direct_error_group_winner', '?')}",
        f"dist={row.get('distributional_group_winner', '?')}",
    ]
    return " | ".join(parts)


def make_speed_error_panel(
    sample_id: int,
    arrays: Dict[str, np.ndarray],
    cnn_lookup: Dict[int, int],
    gan_lookup: Dict[int, int],
    out_path: Path,
    metadata: Dict[int, Dict[str, str]],
    crop_size: Optional[int],
    crop_origin: Tuple[int, int],
) -> None:
    if sample_id not in cnn_lookup or sample_id not in gan_lookup:
        raise KeyError(f"sample_id={sample_id} missing from CNN or GAN idx.npy")

    ci = cnn_lookup[sample_id]
    gi = gan_lookup[sample_id]

    gt = np.asarray(arrays["cnn_gt"][ci])
    gan_gt = np.asarray(arrays["gan_gt"][gi])
    if gt.shape == gan_gt.shape:
        max_gt_diff = float(np.max(np.abs(gt - gan_gt)))
    else:
        max_gt_diff = float("nan")

    cnn = np.asarray(arrays["cnn_sr"][ci])
    gan = np.asarray(arrays["gan_sr"][gi])

    y0, x0 = crop_origin
    gt_s = crop_field(speed(gt), y0, x0, crop_size)
    cnn_s = crop_field(speed(cnn), y0, x0, crop_size)
    gan_s = crop_field(speed(gan), y0, x0, crop_size)

    cnn_err = np.abs(cnn_s - gt_s)
    gan_err = np.abs(gan_s - gt_s)

    vmin = float(np.nanmin([gt_s.min(), cnn_s.min(), gan_s.min()]))
    vmax = float(np.nanmax([gt_s.max(), cnn_s.max(), gan_s.max()]))
    err_vmax = float(np.nanmax([cnn_err.max(), gan_err.max()]))

    out_path.parent.mkdir(parents=True, exist_ok=True)

    fig, axes = plt.subplots(1, 5, figsize=(18, 4.2), constrained_layout=True)
    fig.suptitle(metadata_title(sample_id, metadata), fontsize=11)

    panels = [
        ("GT speed", gt_s, vmin, vmax),
        ("CNN speed", cnn_s, vmin, vmax),
        ("GAN speed", gan_s, vmin, vmax),
        ("|CNN-GT|", cnn_err, 0.0, err_vmax),
        ("|GAN-GT|", gan_err, 0.0, err_vmax),
    ]

    for ax, (title, data, lo, hi) in zip(axes, panels):
        im = ax.imshow(data, origin="lower", vmin=lo, vmax=hi)
        ax.set_title(title, fontsize=10)
        ax.set_xticks([])
        ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    if crop_size is None:
        subtitle = f"full field; max GT CNN/GAN diff={max_gt_diff:.3e}"
    else:
        subtitle = f"crop y={y0}:{y0+crop_size}, x={x0}:{x0+crop_size}; max GT CNN/GAN diff={max_gt_diff:.3e}"
    fig.text(0.5, 0.01, subtitle, ha="center", fontsize=9)

    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def make_uv_panel(
    sample_id: int,
    arrays: Dict[str, np.ndarray],
    cnn_lookup: Dict[int, int],
    gan_lookup: Dict[int, int],
    out_path: Path,
    crop_size: Optional[int],
    crop_origin: Tuple[int, int],
) -> None:
    ci = cnn_lookup[sample_id]
    gi = gan_lookup[sample_id]

    gt = np.asarray(arrays["cnn_gt"][ci])
    cnn = np.asarray(arrays["cnn_sr"][ci])
    gan = np.asarray(arrays["gan_sr"][gi])

    y0, x0 = crop_origin
    if crop_size is not None:
        sl = (slice(y0, y0 + crop_size), slice(x0, x0 + crop_size))
        gt = gt[sl]
        cnn = cnn[sl]
        gan = gan[sl]

    fields = [
        ("GT u", gt[..., 0]), ("CNN u", cnn[..., 0]), ("GAN u", gan[..., 0]),
        ("GT v", gt[..., 1]), ("CNN v", cnn[..., 1]), ("GAN v", gan[..., 1]),
    ]

    u_min = float(np.nanmin([fields[i][1].min() for i in [0, 1, 2]]))
    u_max = float(np.nanmax([fields[i][1].max() for i in [0, 1, 2]]))
    v_min = float(np.nanmin([fields[i][1].min() for i in [3, 4, 5]]))
    v_max = float(np.nanmax([fields[i][1].max() for i in [3, 4, 5]]))

    out_path.parent.mkdir(parents=True, exist_ok=True)

    fig, axes = plt.subplots(2, 3, figsize=(12, 7), constrained_layout=True)
    fig.suptitle(f"sample {sample_id}: u/v components", fontsize=11)

    for ax, (title, data) in zip(axes.ravel(), fields):
        lo, hi = (u_min, u_max) if " u" in title else (v_min, v_max)
        im = ax.imshow(data, origin="lower", vmin=lo, vmax=hi)
        ax.set_title(title, fontsize=10)
        ax.set_xticks([])
        ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def make_contact_sheet(sample_ids: Sequence[int], panel_dir: Path, out_path: Path, title: str, max_cols: int = 3) -> None:
    """Make a lightweight contact sheet from already generated PNG files."""
    from PIL import Image, ImageDraw

    images = []
    labels = []
    for sid in sample_ids:
        p = panel_dir / f"sample_{sid:03d}_speed_error_crop.png"
        if p.exists():
            img = Image.open(p).convert("RGB")
            img.thumbnail((600, 180))
            images.append(img.copy())
            labels.append(str(sid))
            img.close()

    if not images:
        return

    cols = min(max_cols, len(images))
    rows = math.ceil(len(images) / cols)
    cell_w = max(img.width for img in images)
    cell_h = max(img.height for img in images) + 24
    sheet = Image.new("RGB", (cols * cell_w, rows * cell_h + 40), "white")
    draw = ImageDraw.Draw(sheet)
    draw.text((10, 10), title, fill="black")

    for idx, (img, label) in enumerate(zip(images, labels)):
        r = idx // cols
        c = idx % cols
        x = c * cell_w
        y = 40 + r * cell_h
        draw.text((x + 8, y + 2), f"sample {label}", fill="black")
        sheet.paste(img, (x, y + 22))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(out_path)


def write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: List[str] = []
    for row in rows:
        for k in row:
            if k not in fieldnames:
                fieldnames.append(k)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def choose_samples(preset: str, group_map: Dict[str, List[int]], groups_dir: Path,
                   max_candidate: int, max_distributional: int) -> Tuple[List[int], Dict[int, List[str]]]:
    sample_to_sets: Dict[int, List[str]] = defaultdict(list)

    def add(name: str, ids: Iterable[int]) -> None:
        for sid in ids:
            sample_to_sets[int(sid)].append(name)

    add("phase1_core_contrast", CORE_CONTRAST_SAMPLES)
    add("mt_primary_controls", MT_PRIMARY_CONTROL_SAMPLES)
    add("neartie_topology_validator_disagreement", group_map.get("neartie_topology_validator_disagreement", []))
    add("mt_gan_diagnostic", group_map.get("mt_gan_diagnostic", []))
    add("topology_consensus_cnn", group_map.get("topology_consensus_cnn", []))

    if preset == "starter":
        ids = CORE_CONTRAST_SAMPLES
        return ordered_unique(ids), sample_to_sets

    recommended = group_map.get("recommended_visual_inspection_unique", [])
    if preset == "paper_audit":
        if recommended:
            add("recommended_visual_inspection_unique", recommended)
            ids = recommended + CORE_CONTRAST_SAMPLES + TOPOLOGY_CONSENSUS_CNN_SAMPLES
        else:
            cand = group_map.get("candidate_structural_hallucination_signature", [])[:max_candidate]
            dist = group_map.get("gan_distributional_cases", [])[:max_distributional]
            add("candidate_structural_hallucination_top", cand)
            add("gan_distributional_top", dist)
            ids = CORE_CONTRAST_SAMPLES + MT_GAN_DIAGNOSTIC_SAMPLES + TOPOLOGY_CONSENSUS_CNN_SAMPLES + cand + dist
        return ordered_unique(ids), sample_to_sets

    # all_observation_groups
    all_ids: List[int] = []
    for name, ids in sorted(group_map.items()):
        if name.startswith("recommended"):
            continue
        add(name, ids)
        all_ids.extend(ids)
    all_ids.extend(CORE_CONTRAST_SAMPLES)
    return ordered_unique(all_ids), sample_to_sets


def make_index_html(outdir: Path, manifest_rows: List[Dict[str, object]]) -> None:
    rows_html = []
    for row in manifest_rows:
        sample_id = int(row["sample_idx"])
        rel = html.escape(str(row["crop_panel_path"]))
        groups = html.escape(str(row.get("groups", "")))
        suggested = html.escape(str(row.get("suggested_question", "")))
        rows_html.append(
            f"<tr><td>{sample_id}</td><td>{groups}</td><td>{suggested}</td>"
            f"<td><a href='{rel}'><img src='{rel}' width='420'></a></td></tr>"
        )

    text = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>TopoAware SR visual inspection index</title>
<style>
body {{ font-family: sans-serif; margin: 24px; }}
table {{ border-collapse: collapse; width: 100%; }}
td, th {{ border: 1px solid #ddd; padding: 6px; vertical-align: top; }}
th {{ background: #f2f2f2; }}
</style>
</head>
<body>
<h1>TopoAware SR visual inspection index</h1>
<p>Each panel shows: GT speed | CNN speed | GAN speed | |CNN-GT| |GAN-GT|.</p>
<table>
<thead><tr><th>Sample</th><th>Groups</th><th>Question</th><th>Panel</th></tr></thead>
<tbody>
{''.join(rows_html)}
</tbody>
</table>
</body>
</html>
"""
    (outdir / "index.html").write_text(text)


def suggested_question_for_sample(sample_id: int, groups: List[str]) -> str:
    g = set(groups)
    if "neartie_topology_validator_disagreement" in g:
        return "Near-tie edge case: do PD/MT reward real GAN structure or visually sharp artifacts?"
    if "mt_gan_diagnostic" in g:
        return "MT favors GAN: is GAN structurally closer to GT, or sharper but misaligned?"
    if "candidate_structural_hallucination_signature" in g:
        return "PD favors GAN but MT favors CNN: are GAN features plausible but hierarchically/spatially misaligned?"
    if "gan_distributional_cases" in g:
        return "Distributional metrics favor GAN: does GAN preserve multiscale/tail structure better?"
    if "mt_primary_controls" in g:
        return "Control: does CNN look smoother but more faithful to GT?"
    return "Inspect GT/CNN/GAN structure and error maps."


def main() -> None:
    args = parse_args()
    repo_root = discover_repo_root(args.repo_root)

    cnn_dir = resolve_project_path(args.cnn_dir, repo_root)
    gan_dir = resolve_project_path(args.gan_dir, repo_root)
    groups_dir = resolve_project_path(args.groups_dir, repo_root)
    outdir = resolve_project_path(args.outdir, repo_root)

    print(f"repo_root={repo_root}")
    print(f"cnn_dir={cnn_dir}")
    print(f"gan_dir={gan_dir}")
    print(f"groups_dir={groups_dir}")
    print(f"outdir={outdir}")

    outdir.mkdir(parents=True, exist_ok=True)

    group_map = build_group_map(groups_dir)
    metadata = load_per_sample_metadata(groups_dir)
    sample_ids, sample_to_sets = choose_samples(
        args.preset, group_map, groups_dir, args.max_candidate_hallucination, args.max_gan_distributional
    )

    arrays = load_arrays(cnn_dir, gan_dir)
    cnn_lookup = build_idx_lookup(arrays["cnn_idx"])
    gan_lookup = build_idx_lookup(arrays["gan_idx"])

    y0, x0 = args.crop_origin
    crop_dir = outdir / "panels_crop160"
    full_dir = outdir / "panels_full"
    uv_dir = outdir / "panels_uv"
    contact_dir = outdir / "contact_sheets"

    manifest_rows: List[Dict[str, object]] = []

    for sid in sample_ids:
        groups = sorted(set(sample_to_sets.get(sid, []) + [
            name for name, ids in group_map.items() if sid in set(ids)
        ]))
        crop_path = crop_dir / f"sample_{sid:03d}_speed_error_crop.png"
        make_speed_error_panel(
            sid, arrays, cnn_lookup, gan_lookup, crop_path, metadata,
            crop_size=args.crop_size, crop_origin=(y0, x0)
        )

        full_path = ""
        if args.include_full_panels:
            p = full_dir / f"sample_{sid:03d}_speed_error_full.png"
            make_speed_error_panel(
                sid, arrays, cnn_lookup, gan_lookup, p, metadata,
                crop_size=None, crop_origin=(0, 0)
            )
            full_path = str(p.relative_to(outdir))

        uv_path = ""
        if args.include_uv_panels:
            p = uv_dir / f"sample_{sid:03d}_uv_crop.png"
            make_uv_panel(
                sid, arrays, cnn_lookup, gan_lookup, p,
                crop_size=args.crop_size, crop_origin=(y0, x0)
            )
            uv_path = str(p.relative_to(outdir))

        row_meta = metadata.get(sid, {})
        manifest_rows.append({
            "sample_idx": sid,
            "groups": ";".join(groups),
            "suggested_question": suggested_question_for_sample(sid, groups),
            "ssim_winner": row_meta.get("ssim_winner", ""),
            "psnr_winner": row_meta.get("psnr_winner", ""),
            "pd_winner": row_meta.get("pd_winner", ""),
            "mt_winner": row_meta.get("mt_winner", ""),
            "direct_error_group_winner": row_meta.get("direct_error_group_winner", ""),
            "distributional_group_winner": row_meta.get("distributional_group_winner", ""),
            "tail_group_winner": row_meta.get("tail_group_winner", ""),
            "configured_physics_group_winner": row_meta.get("configured_physics_group_winner", ""),
            "crop_panel_path": str(crop_path.relative_to(outdir)),
            "full_panel_path": full_path,
            "uv_panel_path": uv_path,
        })

    write_csv(outdir / "visual_inspection_manifest.csv", manifest_rows)

    template_rows = []
    for r in manifest_rows:
        template_rows.append({
            **r,
            "visual_winner": "",
            "gan_sharper": "",
            "gan_artifact_or_hallucination_candidate": "",
            "cnn_oversmoothed": "",
            "which_is_closer_to_gt_structure": "",
            "notes": "",
        })
    write_csv(outdir / "visual_observation_template.csv", template_rows)

    # Contact sheets for core groups.
    for name, ids in [
        ("phase1_core_contrast", CORE_CONTRAST_SAMPLES),
        ("neartie_topology_validator_disagreement", group_map.get("neartie_topology_validator_disagreement", [])),
        ("mt_gan_diagnostic", group_map.get("mt_gan_diagnostic", [])),
        ("topology_consensus_cnn", group_map.get("topology_consensus_cnn", [])),
    ]:
        ids_present = [sid for sid in ids if sid in sample_ids]
        if ids_present:
            make_contact_sheet(ids_present, crop_dir, contact_dir / f"{name}_contact_sheet.png", name)

    make_index_html(outdir, manifest_rows)

    readme = f"""# Visual Inspection Panels

Generated by `generate_visual_inspection_panels.py`.

## Input directories

- CNN: `{cnn_dir}`
- GAN: `{gan_dir}`
- observation groups: `{groups_dir}`

## Output

- `panels_crop160/`: default GT/CNN/GAN speed and error panels using the {args.crop_size}x{args.crop_size} crop
- `visual_inspection_manifest.csv`: sample list, group membership, and panel paths
- `visual_observation_template.csv`: copy/edit this file while recording visual observations
- `contact_sheets/`: quick overview sheets for core groups
- `index.html`: browser-viewable index of generated panels

## Recommended inspection order

1. Samples 8, 12, 25: near-tie topology-consensus-GAN / validator-disagreement cases.
2. Samples 27, 31, 37, 39, 29, 32: MT-primary / CNN-control cases.
3. All MT-GAN diagnostic samples.
4. Top candidate PD-GAN / MT-CNN disagreement samples.
5. Top GAN-distributional cases.

## Interpretation reminder

These panels should be used to determine whether GAN-favored structure is
physically meaningful, merely visually sharp, or spatially/hierarchically
misaligned relative to GT. The safest claim is that PD-MT disagreement provides
candidate structural-hallucination cases for visual inspection, not automatic
proof of hallucination.
"""
    (outdir / "README_visual_inspection.md").write_text(readme)

    print(f"Wrote {len(sample_ids)} unique sample panels.")
    print(f"manifest={outdir / 'visual_inspection_manifest.csv'}")
    print(f"template={outdir / 'visual_observation_template.csv'}")
    print(f"index={outdir / 'index.html'}")
    print(f"panels={crop_dir}")


if __name__ == "__main__":
    main()
